class RectVis {

    constructor(parentElement) {
        this.parentElement = parentElement;

        this.initVis()
    }

    initVis() {
        let indicators = ['unexplained weight loss', 'fever', 'fatigue', 'pain', 'skin changes', 'change in bowel habits or bladder function', 'unusual bleeding or discharge', 'anemia']
        let vis = this
        vis.margin = {top: 20, right: 20, bottom: 20, left: 40};
        // vis.width = document.getElementById(vis.parentElement).getBoundingClientRect().width - vis.margin.left - vis.margin.right;
        vis.width = 1000
        vis.height = 500;

        // init drawing area
        vis.svg = d3.select("#" + vis.parentElement).append("svg")
            .attr("width", vis.width + vis.margin.left + vis.margin.right)
            .attr("height", vis.height + vis.margin.top + vis.margin.bottom)
            .append('g')
            .attr('transform', `translate (${vis.margin.left}, ${vis.margin.top})`);

        // vis.svg.append('g')
        //     .attr('class', 'title bar-title')
        //     .append('text')
        //     .text('Circle Chart')
        //     .attr('transform', `translate(${vis.width / 2}, 0)`)
        //     .attr('text-anchor', 'middle');

        vis.svg.selectAll('rect')
            .data(indicators)
            .enter().append('rect')
            .attr('width',120)
            .attr('height',180)
            .attr('x',(d,i)=>i%4 * 200 + 125)
            .attr('y',(d,i)=>Math.floor(i/4) * 225 + 40)
            .attr('fill','#D8C3A4')
            .on('click', function(d,i) {
                let index = indicators.indexOf(i)
                vis.svg.append('rect')
                    .attr('width',120)
                    .attr('height',180)
                    .attr('x',(d,i)=>index%4 * 200 + 125)
                    .attr('y',(d,i)=>Math.floor(index/4) * 225 + 40)
                    .attr('fill','#D8C3A4')
                if (index === 0) {
                    vis.svg.append('text')
                        .attr('x',130)
                        .attr('y', 100+5)
                        .text('Unexplained weight')
                        .attr('font-size','12px')
                    vis.svg.append('text')
                        .attr('x',135)
                        .attr('y', 110+5)
                        .text('loss is associated')
                        .attr('font-size','12px')
                    vis.svg.append('text')
                        .attr('x',130)
                        .attr('y', 120+5)
                        .text('with cancers of the')
                        .attr('font-size','12px')
                    vis.svg.append('text')
                        .attr('x',155)
                        .attr('y', 130+5)
                        .text('esophagus,')
                        .attr('font-size','12px')
                    vis.svg.append('text')
                        .attr('x',135)
                        .attr('y', 140+5)
                        .text('stomach, lung, or')
                        .attr('font-size','12px')
                    vis.svg.append('text')
                        .attr('x',160)
                        .attr('y', 150+5)
                        .text('pancreas')
                        .attr('font-size','12px')
                }
                else if (index === 1) {
                    vis.svg.append('text')
                        .attr('x',328)
                        .attr('y',110)
                        .text('Generally, all cancer')
                        .attr('font-size','12px')
                    vis.svg.append('text')
                        .attr('x',330)
                        .attr('y',120)
                        .text('patients will have a')
                        .attr('font-size','12px')
                    vis.svg.append('text')
                        .attr('x',330)
                        .attr('y',130)
                        .text('fever at some point')
                        .attr('font-size','12px')
                    vis.svg.append('text')
                        .attr('x',328)
                        .attr('y',140)
                        .text('as the tumor affects')
                        .attr('font-size','12px')
                    vis.svg.append('text')
                        .attr('x',330)
                        .attr('y',150)
                        .text('the immune system')
                        .attr('font-size','12px')
                }
                else if (index === 2) {
                    vis.svg.append('text')
                        .attr('x',540)
                        .attr('y',100)
                        .text('It is a significant')
                        .attr('font-size','12px')
                    vis.svg.append('text')
                        .attr('x',540)
                        .attr('y',110)
                        .text('cancer symptom')
                        .attr('font-size','12px')
                    vis.svg.append('text')
                        .attr('x',543)
                        .attr('y',120)
                        .text('common in the')
                        .attr('font-size','12px')
                    vis.svg.append('text')
                        .attr('x',543)
                        .attr('y',130)
                        .text('early stages of')
                        .attr('font-size','12px')
                    vis.svg.append('text')
                        .attr('x',532)
                        .attr('y',140)
                        .text('leukemia and some')
                        .attr('font-size','12px')
                    vis.svg.append('text')
                        .attr('x',537)
                        .attr('y',150)
                        .text('stomach or colon')
                        .attr('font-size','12px')
                    vis.svg.append('text')
                        .attr('x',560)
                        .attr('y',160)
                        .text('cancers')
                        .attr('font-size','12px')
                }
                else if (index === 3) {
                    vis.svg.append('text')
                        .attr('x',730)
                        .attr('y',110)
                        .text('Particular pains are')
                        .attr('font-size','12px')
                    vis.svg.append('text')
                        .attr('x',740)
                        .attr('y',120)
                        .text('usually signs of')
                        .attr('font-size','12px')
                    vis.svg.append('text')
                        .attr('x',740)
                        .attr('y',130)
                        .text('cancer such as')
                        .attr('font-size','12px')
                    vis.svg.append('text')
                        .attr('x',760)
                        .attr('y',140)
                        .text('testicular')
                        .attr('font-size','12px')
                    vis.svg.append('text')
                        .attr('x',742)
                        .attr('y',150)
                        .text('or bone cancer')
                        .attr('font-size','12px')
                }
                else if (index === 4) {
                    vis.svg.append('text')
                        .attr('x',150)
                        .attr('y',340)
                        .text('The odds of')
                        .attr('font-size','12px')
                    vis.svg.append('text')
                        .attr('x',133)
                        .attr('y',350)
                        .text('eliminating various')
                        .attr('font-size','12px')
                    vis.svg.append('text')
                        .attr('x',128)
                        .attr('y',360)
                        .text('types of skin cancer')
                        .attr('font-size','12px')
                    vis.svg.append('text')
                        .attr('x',132)
                        .attr('y',370)
                        .text('are incredibly high')
                        .attr('font-size','12px')
                    vis.svg.append('text')
                        .attr('x',128)
                        .attr('y',380)
                        .text('when detected early')
                        .attr('font-size','12px')
                }
                else if (index === 5) {
                    vis.svg.append('text')
                        .attr('x',355)
                        .attr('y',330)
                        .text('Long-term')
                        .attr('font-size','12px')
                    vis.svg.append('text')
                        .attr('x',347)
                        .attr('y',340)
                        .text('constipation,')
                        .attr('font-size','12px')
                    vis.svg.append('text')
                        .attr('x',345)
                        .attr('y',350)
                        .text('diarrhea, or a')
                        .attr('font-size','12px')
                    vis.svg.append('text')
                        .attr('x',340)
                        .attr('y',360)
                        .text('change in stool')
                        .attr('font-size','12px')
                    vis.svg.append('text')
                        .attr('x',335)
                        .attr('y',370)
                        .text('size may be a sign')
                        .attr('font-size','12px')
                    vis.svg.append('text')
                        .attr('x',350)
                        .attr('y',380)
                        .text('colon cancer')
                        .attr('font-size','12px')
                }
                else if (index === 6) {
                    vis.svg.append('text')
                        .attr('x',532)
                        .attr('y',320)
                        .text('Coughing up blood')
                        .attr('font-size','12px')
                    vis.svg.append('text')
                        .attr('x',535)
                        .attr('y',330)
                        .text('could be a sign of')
                        .attr('font-size','12px')
                    vis.svg.append('text')
                        .attr('x',535)
                        .attr('y',340)
                        .text('lung cancer. Dark,')
                        .attr('font-size','12px')
                    vis.svg.append('text')
                        .attr('x',535)
                        .attr('y',350)
                        .text('black, or blood in')
                        .attr('font-size','12px')
                    vis.svg.append('text')
                        .attr('x',535)
                        .attr('y',360)
                        .text('the stool could be')
                        .attr('font-size','12px')
                    vis.svg.append('text')
                        .attr('x',545)
                        .attr('y',370)
                        .text('a symptom of')
                        .attr('font-size','12px')
                    vis.svg.append('text')
                        .attr('x',545)
                        .attr('y',380)
                        .text('rectal or colon')
                        .attr('font-size','12px')
                    vis.svg.append('text')
                        .attr('x',567)
                        .attr('y',390)
                        .text('cancer')
                        .attr('font-size','12px')
                }
                else if (index === 7) {
                    vis.svg.append('text')
                        .attr('x',750)
                        .attr('y',330)
                        .text('Cancers like')
                        .attr('font-size','12px')
                    vis.svg.append('text')
                        .attr('x',760)
                        .attr('y',340)
                        .text('leukemia,')
                        .attr('font-size','12px')
                    vis.svg.append('text')
                        .attr('x',740)
                        .attr('y',350)
                        .text('lymphoma, and')
                        .attr('font-size','12px')
                    vis.svg.append('text')
                        .attr('x',740)
                        .attr('y',360)
                        .text('multiple myeloma')
                        .attr('font-size','12px')
                    vis.svg.append('text')
                        .attr('x',735)
                        .attr('y',370)
                        .text('can damage your')
                        .attr('font-size','12px')
                    vis.svg.append('text')
                        .attr('x',765)
                        .attr('y',380)
                        .text('marrow')
                        .attr('font-size','12px')
                }
            })

        vis.svg.append('text')
            .attr('x', 140)
            .attr('y', 122)
            .text('Unexplained')
            .on('click',function() {
                vis.svg.append('rect')
                    .attr('width', 120)
                    .attr('height', 180)
                    .attr('x', 0 % 4 * 200 + 125)
                    .attr('y', Math.floor(0 / 4) * 225 + 40)
                    .attr('fill','#D8C3A4')
                vis.svg.append('text')
                    .attr('x',130)
                    .attr('y', 100+5)
                    .text('Unexplained weight')
                    .attr('font-size','12px')
                vis.svg.append('text')
                    .attr('x',135)
                    .attr('y', 110+5)
                    .text('loss is associated')
                    .attr('font-size','12px')
                vis.svg.append('text')
                    .attr('x',130)
                    .attr('y', 120+5)
                    .text('with cancers of the')
                    .attr('font-size','12px')
                vis.svg.append('text')
                    .attr('x',155)
                    .attr('y', 130+5)
                    .text('esophagus,')
                    .attr('font-size','12px')
                vis.svg.append('text')
                    .attr('x',135)
                    .attr('y', 140+5)
                    .text('stomach, lung, or')
                    .attr('font-size','12px')
                vis.svg.append('text')
                    .attr('x',160)
                    .attr('y', 150+5)
                    .text('pancreas')
                    .attr('font-size','12px')
            })
        vis.svg.append('text')
            .attr('x', 155)
            .attr('y', 140)
            .text('Weight')
            .on('click',function() {
                vis.svg.append('rect')
                    .attr('width', 120)
                    .attr('height', 180)
                    .attr('x', 0 % 4 * 200 + 125)
                    .attr('y', Math.floor(0 / 4) * 225 + 40)
                    .attr('fill','#D8C3A4')
                vis.svg.append('text')
                    .attr('x',130)
                    .attr('y', 100+5)
                    .text('Unexplained weight')
                    .attr('font-size','12px')
                vis.svg.append('text')
                    .attr('x',135)
                    .attr('y', 110+5)
                    .text('loss is associated')
                    .attr('font-size','12px')
                vis.svg.append('text')
                    .attr('x',130)
                    .attr('y', 120+5)
                    .text('with cancers of the')
                    .attr('font-size','12px')
                vis.svg.append('text')
                    .attr('x',155)
                    .attr('y', 130+5)
                    .text('esophagus,')
                    .attr('font-size','12px')
                vis.svg.append('text')
                    .attr('x',135)
                    .attr('y', 140+5)
                    .text('stomach, lung, or')
                    .attr('font-size','12px')
                vis.svg.append('text')
                    .attr('x',160)
                    .attr('y', 150+5)
                    .text('pancreas')
                    .attr('font-size','12px')
            })
        vis.svg.append('text')
            .attr('x', 165)
            .attr('y', 158)
            .text('Loss')
            .on('click',function() {
                vis.svg.append('rect')
                    .attr('width', 120)
                    .attr('height', 180)
                    .attr('x', 0 % 4 * 200 + 125)
                    .attr('y', Math.floor(0 / 4) * 225 + 40)
                    .attr('fill','#D8C3A4')
                vis.svg.append('text')
                    .attr('x',130)
                    .attr('y', 100+5)
                    .text('Unexplained weight')
                    .attr('font-size','12px')
                vis.svg.append('text')
                    .attr('x',135)
                    .attr('y', 110+5)
                    .text('loss is associated')
                    .attr('font-size','12px')
                vis.svg.append('text')
                    .attr('x',130)
                    .attr('y', 120+5)
                    .text('with cancers of the')
                    .attr('font-size','12px')
                vis.svg.append('text')
                    .attr('x',155)
                    .attr('y', 130+5)
                    .text('esophagus,')
                    .attr('font-size','12px')
                vis.svg.append('text')
                    .attr('x',135)
                    .attr('y', 140+5)
                    .text('stomach, lung, or')
                    .attr('font-size','12px')
                vis.svg.append('text')
                    .attr('x',160)
                    .attr('y', 150+5)
                    .text('pancreas')
                    .attr('font-size','12px')
            })


        vis.svg.append('text')
            .attr('x',365)
            .attr('y',140)
            .text('Fever')
            .on('click',function() {
                vis.svg.append('rect')
                    .attr('width',120)
                    .attr('height',180)
                    .attr('x',1%4 * 200 + 125)
                    .attr('y',Math.floor(1/4)*225+40)
                    .attr('fill','#D8C3A4')
                vis.svg.append('text')
                    .attr('x',328)
                    .attr('y',110)
                    .text('Generally, all cancer')
                    .attr('font-size','12px')
                vis.svg.append('text')
                    .attr('x',330)
                    .attr('y',120)
                    .text('patients will have a')
                    .attr('font-size','12px')
                vis.svg.append('text')
                    .attr('x',330)
                    .attr('y',130)
                    .text('fever at some point')
                    .attr('font-size','12px')
                vis.svg.append('text')
                    .attr('x',328)
                    .attr('y',140)
                    .text('as the tumor affects')
                    .attr('font-size','12px')
                vis.svg.append('text')
                    .attr('x',330)
                    .attr('y',150)
                    .text('the immune system')
                    .attr('font-size','12px')
        })

        vis.svg.append('text')
            .attr('x',557)
            .attr('y',140)
            .text('Fatigue')
            .on('click',function() {
                vis.svg.append('rect')
                    .attr('width', 120)
                    .attr('height', 180)
                    .attr('x', 2 % 4 * 200 + 125)
                    .attr('y', Math.floor(2 / 4) * 225 + 40)
                    .attr('fill','#D8C3A4')
                vis.svg.append('text')
                    .attr('x',540)
                    .attr('y',100)
                    .text('It is a significant')
                    .attr('font-size','12px')
                vis.svg.append('text')
                    .attr('x',540)
                    .attr('y',110)
                    .text('cancer symptom')
                    .attr('font-size','12px')
                vis.svg.append('text')
                    .attr('x',543)
                    .attr('y',120)
                    .text('common in the')
                    .attr('font-size','12px')
                vis.svg.append('text')
                    .attr('x',543)
                    .attr('y',130)
                    .text('early stages of')
                    .attr('font-size','12px')
                vis.svg.append('text')
                    .attr('x',532)
                    .attr('y',140)
                    .text('leukemia and some')
                    .attr('font-size','12px')
                vis.svg.append('text')
                    .attr('x',537)
                    .attr('y',150)
                    .text('stomach or colon')
                    .attr('font-size','12px')
                vis.svg.append('text')
                    .attr('x',560)
                    .attr('y',160)
                    .text('cancers')
                    .attr('font-size','12px')

            })

        vis.svg.append('text')
            .attr('x',768)
            .attr('y',140)
            .text('Pain')
            .on('click',function() {
                vis.svg.append('rect')
                    .attr('width', 120)
                    .attr('height', 180)
                    .attr('x', 3 % 4 * 200 + 125)
                    .attr('y', Math.floor(3 / 4) * 225 + 40)
                    .attr('fill','#D8C3A4')
                vis.svg.append('text')
                    .attr('x',730)
                    .attr('y',110)
                    .text('Particular pains are')
                    .attr('font-size','12px')
                vis.svg.append('text')
                    .attr('x',740)
                    .attr('y',120)
                    .text('usually signs of')
                    .attr('font-size','12px')
                vis.svg.append('text')
                    .attr('x',740)
                    .attr('y',130)
                    .text('cancer such as')
                    .attr('font-size','12px')
                vis.svg.append('text')
                    .attr('x',760)
                    .attr('y',140)
                    .text('testicular')
                    .attr('font-size','12px')
                vis.svg.append('text')
                    .attr('x',742)
                    .attr('y',150)
                    .text('or bone cancer')
                    .attr('font-size','12px')
            })

        vis.svg.append('text')
            .attr('x',135)
            .attr('y',360)
            .text('Skin Changes')
            .on('click',function() {
                vis.svg.append('rect')
                    .attr('width', 120)
                    .attr('height', 180)
                    .attr('x', 4 % 4 * 200 + 125)
                    .attr('y', Math.floor(4 / 4) * 225 + 40)
                    .attr('fill','#D8C3A4')
                vis.svg.append('text')
                    .attr('x',150)
                    .attr('y',340)
                    .text('The odds of')
                    .attr('font-size','12px')
                vis.svg.append('text')
                    .attr('x',133)
                    .attr('y',350)
                    .text('eliminating various')
                    .attr('font-size','12px')
                vis.svg.append('text')
                    .attr('x',128)
                    .attr('y',360)
                    .text('types of skin cancer')
                    .attr('font-size','12px')
                vis.svg.append('text')
                    .attr('x',132)
                    .attr('y',370)
                    .text('are incredibly high')
                    .attr('font-size','12px')
                vis.svg.append('text')
                    .attr('x',128)
                    .attr('y',380)
                    .text('when detected early')
                    .attr('font-size','12px')
            })

        vis.svg.append('text')
            .attr('x',343)
            .attr('y',330)
            .text('Changes in')
            .on('click',function() {
                vis.svg.append('rect')
                    .attr('width', 120)
                    .attr('height', 180)
                    .attr('x', 5 % 4 * 200 + 125)
                    .attr('y', Math.floor(5 / 4) * 225 + 40)
                    .attr('fill','#D8C3A4')
                vis.svg.append('text')
                    .attr('x',355)
                    .attr('y',330)
                    .text('Long-term')
                    .attr('font-size','12px')
                vis.svg.append('text')
                    .attr('x',347)
                    .attr('y',340)
                    .text('constipation,')
                    .attr('font-size','12px')
                vis.svg.append('text')
                    .attr('x',345)
                    .attr('y',350)
                    .text('diarrhea, or a')
                    .attr('font-size','12px')
                vis.svg.append('text')
                    .attr('x',340)
                    .attr('y',360)
                    .text('change in stool')
                    .attr('font-size','12px')
                vis.svg.append('text')
                    .attr('x',335)
                    .attr('y',370)
                    .text('size may be a sign')
                    .attr('font-size','12px')
                vis.svg.append('text')
                    .attr('x',350)
                    .attr('y',380)
                    .text('colon cancer')
                    .attr('font-size','12px')
            })
        vis.svg.append('text')
            .attr('x',338)
            .attr('y',348)
            .text('Bowel Habits')
            .on('click',function() {
                vis.svg.append('rect')
                    .attr('width', 120)
                    .attr('height', 180)
                    .attr('x', 5 % 4 * 200 + 125)
                    .attr('y', Math.floor(5 / 4) * 225 + 40)
                    .attr('fill','#D8C3A4')
                vis.svg.append('text')
                    .attr('x',355)
                    .attr('y',330)
                    .text('Long-term')
                    .attr('font-size','12px')
                vis.svg.append('text')
                    .attr('x',347)
                    .attr('y',340)
                    .text('constipation,')
                    .attr('font-size','12px')
                vis.svg.append('text')
                    .attr('x',345)
                    .attr('y',350)
                    .text('diarrhea, or a')
                    .attr('font-size','12px')
                vis.svg.append('text')
                    .attr('x',340)
                    .attr('y',360)
                    .text('change in stool')
                    .attr('font-size','12px')
                vis.svg.append('text')
                    .attr('x',335)
                    .attr('y',370)
                    .text('size may be a sign')
                    .attr('font-size','12px')
                vis.svg.append('text')
                    .attr('x',350)
                    .attr('y',380)
                    .text('colon cancer')
                    .attr('font-size','12px')
            })

        vis.svg.append('text')
            .attr('x',345)
            .attr('y',348+18)
            .text('or Bladder')
            .on('click',function() {
                vis.svg.append('rect')
                    .attr('width', 120)
                    .attr('height', 180)
                    .attr('x', 5 % 4 * 200 + 125)
                    .attr('y', Math.floor(5 / 4) * 225 + 40)
                    .attr('fill','#D8C3A4')
                vis.svg.append('text')
                    .attr('x',355)
                    .attr('y',330)
                    .text('Long-term')
                    .attr('font-size','12px')
                vis.svg.append('text')
                    .attr('x',347)
                    .attr('y',340)
                    .text('constipation,')
                    .attr('font-size','12px')
                vis.svg.append('text')
                    .attr('x',345)
                    .attr('y',350)
                    .text('diarrhea, or a')
                    .attr('font-size','12px')
                vis.svg.append('text')
                    .attr('x',340)
                    .attr('y',360)
                    .text('change in stool')
                    .attr('font-size','12px')
                vis.svg.append('text')
                    .attr('x',335)
                    .attr('y',370)
                    .text('size may be a sign')
                    .attr('font-size','12px')
                vis.svg.append('text')
                    .attr('x',350)
                    .attr('y',380)
                    .text('colon cancer')
                    .attr('font-size','12px')
            })

        vis.svg.append('text')
            .attr('x',355)
            .attr('y',348+36)
            .text('Function')
            .on('click',function() {
                vis.svg.append('rect')
                    .attr('width', 120)
                    .attr('height', 180)
                    .attr('x', 5 % 4 * 200 + 125)
                    .attr('y', Math.floor(5 / 4) * 225 + 40)
                    .attr('fill','#D8C3A4')
                vis.svg.append('text')
                    .attr('x',355)
                    .attr('y',330)
                    .text('Long-term')
                    .attr('font-size','12px')
                vis.svg.append('text')
                    .attr('x',347)
                    .attr('y',340)
                    .text('constipation,')
                    .attr('font-size','12px')
                vis.svg.append('text')
                    .attr('x',345)
                    .attr('y',350)
                    .text('diarrhea, or a')
                    .attr('font-size','12px')
                vis.svg.append('text')
                    .attr('x',340)
                    .attr('y',360)
                    .text('change in stool')
                    .attr('font-size','12px')
                vis.svg.append('text')
                    .attr('x',335)
                    .attr('y',370)
                    .text('size may be a sign')
                    .attr('font-size','12px')
                vis.svg.append('text')
                    .attr('x',350)
                    .attr('y',380)
                    .text('colon cancer')
                    .attr('font-size','12px')
            })

        vis.svg.append('text')
            .attr('x',553)
            .attr('y',360-18)
            .text('Unusual')
            .on('click',function() {
                vis.svg.append('rect')
                    .attr('width', 120)
                    .attr('height', 180)
                    .attr('x', 6 % 4 * 200 + 125)
                    .attr('y', Math.floor(6 / 4) * 225 + 40)
                    .attr('fill','#88765E')
                vis.svg.append('text')
                    .attr('x',532)
                    .attr('y',320)
                    .text('Coughing up blood')
                    .attr('font-size','12px')
                vis.svg.append('text')
                    .attr('x',535)
                    .attr('y',330)
                    .text('could be a sign of')
                    .attr('font-size','12px')
                vis.svg.append('text')
                    .attr('x',535)
                    .attr('y',340)
                    .text('lung cancer. Dark,')
                    .attr('font-size','12px')
                vis.svg.append('text')
                    .attr('x',535)
                    .attr('y',350)
                    .text('black, or blood in')
                    .attr('font-size','12px')
                vis.svg.append('text')
                    .attr('x',535)
                    .attr('y',360)
                    .text('the stool could be')
                    .attr('font-size','12px')
                vis.svg.append('text')
                    .attr('x',545)
                    .attr('y',370)
                    .text('a symptom of')
                    .attr('font-size','12px')
                vis.svg.append('text')
                    .attr('x',545)
                    .attr('y',380)
                    .text('rectal or colon')
                    .attr('font-size','12px')
                vis.svg.append('text')
                    .attr('x',567)
                    .attr('y',390)
                    .text('cancer')
                    .attr('font-size','12px')
            })

        vis.svg.append('text')
            .attr('x',545)
            .attr('y',360)
            .text('Bleeding or')
            .on('click',function() {
                vis.svg.append('rect')
                    .attr('width', 120)
                    .attr('height', 180)
                    .attr('x', 6 % 4 * 200 + 125)
                    .attr('y', Math.floor(6 / 4) * 225 + 40)
                    .attr('fill','#D8C3A4')
                vis.svg.append('text')
                    .attr('x',532)
                    .attr('y',320)
                    .text('Coughing up blood')
                    .attr('font-size','12px')
                vis.svg.append('text')
                    .attr('x',535)
                    .attr('y',330)
                    .text('could be a sign of')
                    .attr('font-size','12px')
                vis.svg.append('text')
                    .attr('x',535)
                    .attr('y',340)
                    .text('lung cancer. Dark,')
                    .attr('font-size','12px')
                vis.svg.append('text')
                    .attr('x',535)
                    .attr('y',350)
                    .text('black, or blood in')
                    .attr('font-size','12px')
                vis.svg.append('text')
                    .attr('x',535)
                    .attr('y',360)
                    .text('the stool could be')
                    .attr('font-size','12px')
                vis.svg.append('text')
                    .attr('x',545)
                    .attr('y',370)
                    .text('a symptom of')
                    .attr('font-size','12px')
                vis.svg.append('text')
                    .attr('x',545)
                    .attr('y',380)
                    .text('rectal or colon')
                    .attr('font-size','12px')
                vis.svg.append('text')
                    .attr('x',567)
                    .attr('y',390)
                    .text('cancer')
                    .attr('font-size','12px')
            })

        vis.svg.append('text')
            .attr('x',550)
            .attr('y',360+18)
            .text('Discharge')
            .on('click',function() {
                vis.svg.append('rect')
                    .attr('width', 120)
                    .attr('height', 180)
                    .attr('x', 6 % 4 * 200 + 125)
                    .attr('y', Math.floor(6 / 4) * 225 + 40)
                    .attr('fill','#D8C3A4')
                vis.svg.append('text')
                    .attr('x',532)
                    .attr('y',320)
                    .text('Coughing up blood')
                    .attr('font-size','12px')
                vis.svg.append('text')
                    .attr('x',535)
                    .attr('y',330)
                    .text('could be a sign of')
                    .attr('font-size','12px')
                vis.svg.append('text')
                    .attr('x',535)
                    .attr('y',340)
                    .text('lung cancer. Dark,')
                    .attr('font-size','12px')
                vis.svg.append('text')
                    .attr('x',535)
                    .attr('y',350)
                    .text('black, or blood in')
                    .attr('font-size','12px')
                vis.svg.append('text')
                    .attr('x',535)
                    .attr('y',360)
                    .text('the stool could be')
                    .attr('font-size','12px')
                vis.svg.append('text')
                    .attr('x',545)
                    .attr('y',370)
                    .text('a symptom of')
                    .attr('font-size','12px')
                vis.svg.append('text')
                    .attr('x',545)
                    .attr('y',380)
                    .text('rectal or colon')
                    .attr('font-size','12px')
                vis.svg.append('text')
                    .attr('x',567)
                    .attr('y',390)
                    .text('cancer')
                    .attr('font-size','12px')
            })

        vis.svg.append('text')
            .attr('x',755)
            .attr('y',360)
            .text('Anemia')
            .on('click',function() {
                vis.svg.append('rect')
                    .attr('width', 120)
                    .attr('height', 180)
                    .attr('x', 6 % 4 * 200 + 125)
                    .attr('y', Math.floor(6 / 4) * 225 + 40)
                    .attr('fill','#D8C3A4')
                vis.svg.append('text')
                    .attr('x',750)
                    .attr('y',330)
                    .text('Cancers like')
                    .attr('font-size','12px')
                vis.svg.append('text')
                    .attr('x',760)
                    .attr('y',340)
                    .text('leukemia,')
                    .attr('font-size','12px')
                vis.svg.append('text')
                    .attr('x',740)
                    .attr('y',350)
                    .text('lymphoma, and')
                    .attr('font-size','12px')
                vis.svg.append('text')
                    .attr('x',740)
                    .attr('y',360)
                    .text('multiple myeloma')
                    .attr('font-size','12px')
                vis.svg.append('text')
                    .attr('x',735)
                    .attr('y',370)
                    .text('can damage your')
                    .attr('font-size','12px')
                vis.svg.append('text')
                    .attr('x',765)
                    .attr('y',380)
                    .text('marrow')
                    .attr('font-size','12px')
            })

    }
}